//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.19 at 04:24:18 PM GMT+04:00 
//


package users_soap.api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the users_soap.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: users_soap.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserByUsernameResponse }
     * 
     */
    public GetUserByUsernameResponse createGetUserByUsernameResponse() {
        return new GetUserByUsernameResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link DeleteUserByUsernameRequest }
     * 
     */
    public DeleteUserByUsernameRequest createDeleteUserByUsernameRequest() {
        return new DeleteUserByUsernameRequest();
    }

    /**
     * Create an instance of {@link EditUserByUsernameResponse }
     * 
     */
    public EditUserByUsernameResponse createEditUserByUsernameResponse() {
        return new EditUserByUsernameResponse();
    }

    /**
     * Create an instance of {@link GetAllUsersRequest }
     * 
     */
    public GetAllUsersRequest createGetAllUsersRequest() {
        return new GetAllUsersRequest();
    }

    /**
     * Create an instance of {@link AddSocialRequest }
     * 
     */
    public AddSocialRequest createAddSocialRequest() {
        return new AddSocialRequest();
    }

    /**
     * Create an instance of {@link SocialInfo }
     * 
     */
    public SocialInfo createSocialInfo() {
        return new SocialInfo();
    }

    /**
     * Create an instance of {@link AddSocialResponse }
     * 
     */
    public AddSocialResponse createAddSocialResponse() {
        return new AddSocialResponse();
    }

    /**
     * Create an instance of {@link AddUserRolesRequest }
     * 
     */
    public AddUserRolesRequest createAddUserRolesRequest() {
        return new AddUserRolesRequest();
    }

    /**
     * Create an instance of {@link GetAllRolesRequest }
     * 
     */
    public GetAllRolesRequest createGetAllRolesRequest() {
        return new GetAllRolesRequest();
    }

    /**
     * Create an instance of {@link DeleteUserByUsernameResponse }
     * 
     */
    public DeleteUserByUsernameResponse createDeleteUserByUsernameResponse() {
        return new DeleteUserByUsernameResponse();
    }

    /**
     * Create an instance of {@link EditUserByUsernameRequest }
     * 
     */
    public EditUserByUsernameRequest createEditUserByUsernameRequest() {
        return new EditUserByUsernameRequest();
    }

    /**
     * Create an instance of {@link AddRoleRequest }
     * 
     */
    public AddRoleRequest createAddRoleRequest() {
        return new AddRoleRequest();
    }

    /**
     * Create an instance of {@link RoleInfo }
     * 
     */
    public RoleInfo createRoleInfo() {
        return new RoleInfo();
    }

    /**
     * Create an instance of {@link AddRoleResponse }
     * 
     */
    public AddRoleResponse createAddRoleResponse() {
        return new AddRoleResponse();
    }

    /**
     * Create an instance of {@link GetAllRolesResponse }
     * 
     */
    public GetAllRolesResponse createGetAllRolesResponse() {
        return new GetAllRolesResponse();
    }

    /**
     * Create an instance of {@link DeleteSocialRequest }
     * 
     */
    public DeleteSocialRequest createDeleteSocialRequest() {
        return new DeleteSocialRequest();
    }

    /**
     * Create an instance of {@link GetAllUsersResponse }
     * 
     */
    public GetAllUsersResponse createGetAllUsersResponse() {
        return new GetAllUsersResponse();
    }

    /**
     * Create an instance of {@link AddUserRolesResponse }
     * 
     */
    public AddUserRolesResponse createAddUserRolesResponse() {
        return new AddUserRolesResponse();
    }

    /**
     * Create an instance of {@link AddUserRequest }
     * 
     */
    public AddUserRequest createAddUserRequest() {
        return new AddUserRequest();
    }

    /**
     * Create an instance of {@link DeleteRoleByUserRequest }
     * 
     */
    public DeleteRoleByUserRequest createDeleteRoleByUserRequest() {
        return new DeleteRoleByUserRequest();
    }

    /**
     * Create an instance of {@link GetUserByUsernameRequest }
     * 
     */
    public GetUserByUsernameRequest createGetUserByUsernameRequest() {
        return new GetUserByUsernameRequest();
    }

    /**
     * Create an instance of {@link DeleteRoleByUserResponse }
     * 
     */
    public DeleteRoleByUserResponse createDeleteRoleByUserResponse() {
        return new DeleteRoleByUserResponse();
    }

    /**
     * Create an instance of {@link AddUserResponse }
     * 
     */
    public AddUserResponse createAddUserResponse() {
        return new AddUserResponse();
    }

    /**
     * Create an instance of {@link DeleteSocialResponse }
     * 
     */
    public DeleteSocialResponse createDeleteSocialResponse() {
        return new DeleteSocialResponse();
    }

}
