//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.18 at 11:46:21 PM GMT+04:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://users-soap/api/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package users_soap.api;
