//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.18 at 11:46:21 PM GMT+04:00 
//


package users_soap.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for roleInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="roleInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="nameRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prettyNameRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "roleInfo", propOrder = {
    "id",
    "nameRole",
    "prettyNameRole"
})
public class RoleInfo {

    protected long id;
    @XmlElement(required = true)
    protected String nameRole;
    @XmlElement(required = true)
    protected String prettyNameRole;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the nameRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRole() {
        return nameRole;
    }

    /**
     * Sets the value of the nameRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRole(String value) {
        this.nameRole = value;
    }

    /**
     * Gets the value of the prettyNameRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrettyNameRole() {
        return prettyNameRole;
    }

    /**
     * Sets the value of the prettyNameRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrettyNameRole(String value) {
        this.prettyNameRole = value;
    }

}
